{% set version = "0.2.1" %}

package:
  name: conda-gitenv
  version: {{ version }}

source:
  fn: conda-gitenv-{{ version }}.tar.gz
  url: https://github.com/SciTools/conda-gitenv/archive/v{{ version }}.tar.gz
  sha256: 5f1b4ed3afc954fad06bb8aedab27ee9108cd968bb1b60809fd17e20f9654614

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - gitpython
    - pyyaml
    - conda >=4.1.0
    - conda-build-all
    - conda-build !=2.0.9

test:
  imports:
    - conda_gitenv
  commands:
    - conda gitenv --help
    - conda gitenv resolve --help
    - conda gitenv autotag --help
    - conda gitenv autolabel --help
    - conda gitenv deploy --help

about:
  home: https://github.com/SciTools/conda-gitenv
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Track environment specifications using a git repo.'

extra:
  recipe-maintainers:
    - pelson
    - bjlittle
    - lbdreyer
