travis:
  secure:
    BINSTAR_TOKEN: ceb7yOhJuoJxUYNM0lOHTC7lo3AHaztJUxAN+QdN6rx48J3/dK/5+HqkbkTx9om8gEiHhPiaF+Pkf+hiksWSZ6NIRAyCzMUirx62yoVNBdm/KI6jDQgT67AQMtpnTyR1ZGHc1YqsRAW25fyu5j9D0jmMLw+zT+5oAsOHvokdGm8AryyJLxjMrkzXPumgUCU50ogL4WAINV2vnIrWEhEqosw91qBzb8DYJH246oHOb7eLqx26bGz4ScGJ9ukpX7b+NS+k+xAXHn+HFBdjp4I2rgZ6qL1mSDlptmCdDSEAPBMN6PZZu2HEX4+orwIxyzI9pHhZuuD4unIJ/KLXhIq6b0uXCrCeOmMb1aCi0YDtBzx670i7BPlelMyUpaiTzgwXiOduGGANXuafxXSChrJRkaSgkiOZqxghnZTkYGxNMg943rkukYd9PX/4dTfAOWlGfZWKcptTcWU3z8zY7/9xRFcw7t/ouInQyFAYJ6385SzolQevgfEHBcef9m2LQp4aQCaLUrV1RA7X1R6gpizdMuuUvGufAK9zHpgDvU+ImwNB0lbahdOWeczpQd9YjSZQN7lg2XvJjzgI1Y9sXGDtxQPb5DLmWE3m4OWkdJ7Nz+iZOsV/qd85jWCzJpNchbeUJdclNZKWqwrKoBQ2SOI6PUiKsC047p4XsPnTCJ7R5lY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
