travis:
  secure:
    BINSTAR_TOKEN: Fhsm09CbH89KMQkgKGtnUDT7yulIWtSLEDtgA/wgqnOfe5tyPV6uCk9PF8egGJULiqRcDv5gp+e5hIgwnUGW/9lfoPcwWTv+hwUA/WldQPoJsScuBU6CzzK1h4kLQp9DF54J9scDRPUdSozjxPUPL7J5Kq9oIYBctwSANvjVLEk3AhDmrtATOomiviykO0KcBXsWZC7LngqYylULxX6c0/53qtAXeTJwDjUQ/e3kIKiMw4RM6TibT8c2dm/ifJw6xlwq40CIhcBX7PQJPiFXUfld67Z/8VQkrxIgeOtpvmxQmixuq2xgqRw+ZoBpwz7cM9qE26QsORKcWrSM++43U6Tl+/Cv2QA0ILSKY5y3wy396X1BbNK/97oN/bMpGJDJt++s61FjA0Qh+QZuvAxRyDjR88vvbiLyNlhImmKTGjxEB9yCVKS0/3C9IcFZNA7t9u0SIC7n5/59ai9VpfLTTfxT/aR5YDlB+qMzqlAccGyjgLD7NB/j2G4Jefs8/9AON5R622ad5FWj3DQ+lSSghhsQ2CcGMlsUumtxeDciX2AyaRIefvHe/X3Vfaj3xfVSNT3FJ4sEw77Dv0U9a4AF8bejrLEx5YFeYXv1OMTOfxCxYbKDwXzcr27H+54KDTb3Uspsz89J97UaZtdL5y/buD3bdDgB0woewuWLa+2tE0A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
